spring:
  redis:
    host: localhost
    port: 8989

ustawienia:
  numerIndeksu: 461010
  wycena: "CENA_ZMIENNA"
  zamowienia: "REZERWACJE"
  zaopatrzenie: "RAPORT_SPRZEDAZY"
  wydarzenia: "WYCOFANIE"
  liczbaZadan: 200
